title: Noé J Nava | noejn2
author: Noé J Nava
email: noejn2@illinois.edu
description: I am a Ph.D candidate.
show_excerpts: true # set to true to show excerpts on the homepage

sass:
  sass_dir: _sass
plainwhite:
  name: Noé J Nava
  tagline: Ph.D. candidate
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: normalEconomist
    github: noejn2
    linkedIn: in/nnrnoah

  navigation:
    #- title: About me
    #  url: "https://noejn2.github.io/"
    - title: Current research
      url: "/current-research/current-research"
    - title: CV
      url: "/cv/cv_nava.pdf"
    - title: Create
      url: "https://publish.illinois.edu/createcenter/"

theme: plainwhite

plugins:
  - jekyll-seo-tag
  #  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/figure
