title: Noé J Nava | noejn2
author: Noé J Nava
email: Noe.Nava@usda.gov
description: I am a microeconomist.
show_excerpts: true # set to true to show excerpts on the homepage

sass:
  sass_dir: _sass
plainwhite:
  name: Noé J Nava
  tagline: Microeconomist
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: normalEconomist
    github: Noe-J-Nava
    linkedIn: in/nnrnoah

  navigation:
    #- title: About me
    #  url: "https://noejn2.github.io/"
    - title: Research agenda
      url: "/current-research/current-research"
    - title: CV
      url: "/cv/cv_nava.pdf"
    - title: Blog
      url: "/wk/wk"

theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  #  - jekyll-feed
