title: Noé J Nava | noejn2
author: Noé J Nava
email: noejnava2@gmail.com
description: I write econ papers and code, mostly.
show_excerpts: true # set to true to show excerpts on the homepage

sass:
  sass_dir: _sass
plainwhite:
  name: Noé J Nava
  tagline: Microeconomist
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    mail: "noejnava2@gmail.com"
    github: noejn2
    linkedIn: in/nnrnoah
    calendar: "https://calendly.com/your-calendar-link"

  navigation:
    - title: About me
      url: "https://noejn2.github.io/"
    - title: CV
      url: "/cv/cv_nava.pdf"
    - title: " "
      url: "#"
    - title: US Domestic Ag. Trade
      url: https://noejnava2.shinyapps.io/us_ag_flows_gravityge/
    - title: gravityGE
      url: "project-descriptions/gravityGE.md"
    - title: Statistical Inference
      url: https://noejnava2.shinyapps.io/us_ag_flows_gravityge/

theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
